### PR TITLE
Anchoring h3 with id for lateral menu fix

### PR DESCRIPTION
**Pull request by knabben**

### CODE REVIEW

**Comment by tisba** [comment]
Hey @knabben, thanks for this change! I'm not really a front end guy, but I thought it's discouraged these days to `id` for this, instead of `name`.

Otherwise, :shipit: :)

**Comment by knabben** [comment]
http://www.w3.org/html/wg/drafts/html/master/browsers.html#scroll-to-fragid

Yeah, I it is fine the ID on any DOM, well, in fact it is applied on graphs template already.

Thanks

**Comment by tisba** [comment]
I'd say, ship it :) :shipit:

**Pull request merged**
