### PR TITLE
use debian compatibility level 9 for 'make deb'

### PR DESCRIPTION
**Pull request by zitune**
debhelper is now at least on version 9 on debian oldstable and stable.

this changes allow the build of deb package on debian.

Built packages can be found on bearstech's apt repo : https://deb.bearstech.com/

### CODE REVIEW

**Comment by tisba** [comment]
I'm not really into debian packaging. Can you maybe have a quick look here, @nniclausse?

**Comment by nniclausse** [comment]
seems fine. the PR if for master though

**Comment by tisba** [comment]
Ah, you are right! Can you change the target branch to `develop` please, @zitune?

**Comment by tisba** [comment]
*duh*. I just realised, that I can change the target branch myself ;)

**Pull request merged**
